package com.example.enwords;
import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;

import java.util.HashMap;

/** Класс для создания страницы выбора категории */
public class MainActivity2 extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main2);
    }
    Category category;
    /**Выбор категории теста Shopping
     * @param view Внешнее представление кнопки 1*/
    public void onButtonClickCategory1(View view) {
        HashMap<String, String> shopping  = new HashMap<>();
        shopping.put("shop [ʃɒp]", "магазин");
        shopping.put("clothes [kloʊðz]", "одежда");
        shopping.put("discount [ˈdiskaʊnt]", "скидка");
        shopping.put("shop assistant [ʃɒp əˈsistənt]", "продавец");
        shopping.put("purchase [ˈpəːtʃis]", "покупка");
        shopping.put("sale [seil]", "продажа");
        shopping.put("cashier [kæˈʃiə]", "кассир");
        shopping.put("receipt [riˈsiːt]", "чек");
        shopping.put("cash [kæʃ]", "наличные");
        shopping.put("credit card [ˈkrɛdit kɑːd]", "кредитная карта");
        shopping.put("delivery [diˈlivəri]", "доставка");
        shopping.put("T-shirt [ˈtiːʃəːt]", "футболка");
        shopping.put("shirt [ʃəːt]", "рубашка");
        shopping.put("trousers [ˈtraʊzəz]", "брюки");
        shopping.put("bag [bæɡ]", "сумка");
        shopping.put("wool [wʊl]", "шерсть");
        shopping.put("cotton [ˈkɑːtn]", "хлопок");
        shopping.put("leather [ˈlɛðə]", "кожа");
        shopping.put("jacket [ˈdʒakit]", "куртка");
        shopping.put("shoes [ʃuːz]", "туфли");
        shopping.put("jeans [dʒiːnz]", "джинсы");
        shopping.put("shorts [ʃɔːts]", "шорты");
        shopping.put("socks [ˈsɒks]", "носки");
        shopping.put("underwear [ˈʌndəwɛː]", "нижнее белье");
        shopping.put("money [ˈmʌni]", "деньги");
        shopping.put("trolley [ˈtrɒli]", "тележка");
        shopping.put("basket [ˈbɑːskit]", "корзина");
        shopping.put("fitting room [ˈfitiŋ ruːm]", "примерочная");
        shopping.put("chip [tʃip]", "дешевый");
        shopping.put("expensive [ikˈspɛnsiv]", "дорогой");
        shopping.put("coins [kɔinz]", "монеты");
        shopping.put("price [prʌis]", "цена");
        shopping.put("wallet [ˈwɑːlit]", "мужской кошелек");
        shopping.put("escalator [ˈeskəleitər]", "эскалатор");
        shopping.put("lift [lift]", "лифт");
        shopping.put("products [ˈprɑːdəkts]", "продукты");
        shopping.put("bookshop [ˈbʊkʃɑːp]", "книжный магазин");
        shopping.put("supermarket [ˈsuːpərmɑːrkət]", "супермаркет");
        shopping.put("pet shop [pet ʃɑːp]", "зоомагазин");
        shopping.put("tea-house [ˈtiːhaʊs]", "чайный магазин");
        shopping.put("post office [pəʊst ˈɔːfis]", "почтовое отделение");
        shopping.put("market [ˈmɑːrkit]", "рынок");
        shopping.put("record shop [ˈrekərd ʃɑːp]", "музыкальный магазин");
        shopping.put("scarf [skɑːrf]", "шарф");
        shopping.put("toy store [tɔi stɔːr]", "магазин игрушек");
        shopping.put("hat [hæt]", "шапка");
        shopping.put("chemist [ˈkemist]", "аптека");
        shopping.put("online store [ɒnˈlain stɔːr]", "онлайн-магазин");
        shopping.put("hoody [ˈhʊdi]", "толстовка");
        shopping.put("manager [ˈmænidʒər]", "менеджер");
        shopping.put("blouse [blaʊs]", "кофта");
        shopping.put("rip-off [ˈrip ɒf]", "грабеж");
        shopping.put("bargain [ˈbɑːrɡən]", "выгодная покупка");
        shopping.put("price tag [prais tæɡ]", "ценник");
        shopping.put("department store [diˈpɑːrtmənt stɔːr]", "универмаг");
        shopping.put("bakery [ˈbeikəri]", "булочная");
        shopping.put("stationary shop [ˈsteiʃənerɪ ʃɑːp]", "магазин с канцелярией");
        shopping.put("florist shop [ˈflɔːrist ʃɑːp]", "цветочный магазин");
        shopping.put("clearance sale [ˈklirəns seil]", "полная распродажа");
        shopping.put("label [ˈleibl]", "ярлык");
        shopping.put("stall [stɔːl]", "киоск");
        shopping.put("booth [buːθ]", "ларек");
        shopping.put("gloves [ɡlʌvz]", "перчатки");
        category = new Category(shopping);
        Intent intent3 =  new  Intent(this, MainActivity3.class);
        intent3.putExtra(Category.class.getSimpleName(),category);
        startActivity(intent3);
    }
    /**Выбор категории теста Verbs
     *@param view  Внешнее представление кнопки 2*/
    public void onButtonClickCategory2(View view) {
        HashMap<String, String> verb  = new HashMap<>();
        verb.put("do [duː]", "делать");
        verb.put("go [ɡəʊ]", "идти");
        verb.put("work [wɜːk]", "работать");
        verb.put("eat [iːt]", "кушать");
        verb.put("see [siː]", "видеть");
        verb.put("watch [wɒtʃ]", "смотреть");
        verb.put("think [θiŋk]", "думать");
        verb.put("buy [bai]", "покупать");
        verb.put("choose [tʃuːz]", "выбирать");
        verb.put("say [sei]", "сказать");
        verb.put("speak [spiːk]", "разговаривать");
        verb.put("feel [fiːl]", "чувствовать");
        verb.put("play [plei]", "играть");
        verb.put("teach [tiːtʃ]", "учить кого-то");
        verb.put("sleep [sliːp]", "спать");
        verb.put("give [ɡiv]", "давать");
        verb.put("take [teik]", "брать");
        verb.put("have [hæv]", "иметь");
        verb.put("hear [hiə]", "слышать");
        verb.put("love [lʌv]", "любить");
        verb.put("live [liv]", "жить");
        verb.put("listen [ˈlisn]", "слушать");
        verb.put("want [wɒnt]", "хотеть");
        verb.put("use [juːz]", "использовать");
        verb.put("ask [ɑːsk]", "спрашивать");
        verb.put("get [ɡet]", "получать");
        verb.put("run [rʌn]", "бежать");
        verb.put("pay [pei]", "платить");
        verb.put("help [help]", "помогать");
        verb.put("win [win]", "побеждать");
        verb.put("lose [luːz]", "терять");
        verb.put("sell [sel]", "продавать");
        verb.put("kill [kil]", "убивать");
        verb.put("cut [kʌt]", "резать");
        verb.put("stop [stɒp]", "остановить");
        verb.put("travel [ˈtrævl]", "путешествовать");
        verb.put("drive [draiv]", "ехать");
        verb.put("accept [əkˈsept]","принимать");
        verb.put("add [æd]","добавлять");
        verb.put("agree [əˈɡriː]","соглашаться");
        verb.put("answer [ˈɑːnsə]","отвечать");
        verb.put("become [biˈkʌm]","становиться");
        verb.put("begin [biˈɡin]","начинать");
        verb.put("believe [biˈliːv]","верить");
        verb.put("borrow [ˈbɒrəʊ]","занимать");
        verb.put("break [breik]","ломать");
        verb.put("cancel [ˈkænsl]","отменять");
        verb.put("change [tʃeindʒ]","менять");
        verb.put("clean [kliːn]","чистить");
        verb.put("close [kləʊz]","закрывать");
        verb.put("come [kʌm]","приходить");
        verb.put("count [kaʊnt]","считать");
        verb.put("dance [dɑːns]","танцевать");
        verb.put("decide [diˈsaid]","решать");
        verb.put("drink [driŋk]","пить");
        verb.put("fly [flai]","летать");
        verb.put("learn [lɜːn]","учить");
        verb.put("lie [lai]","лгать");
        verb.put("own [əʊn]","иметь");
        verb.put("open [ˈəʊpən]","открывать");
        verb.put("read [riːd]","читать");
        verb.put("remember [riˈmembə]","помнить");
        verb.put("swim [swim]","плыть");
        verb.put("write [rait]","писать");
        verb.put("wear [weə]","носить");
        verb.put("try [trai]","пробовать");
        verb.put("translate [trænsˈleit]","переводить");
        category = new Category(verb);
        Intent intent3 =  new  Intent(this, MainActivity3.class);
        intent3.putExtra(Category.class.getSimpleName(),category);
        startActivity(intent3);
    }
    /**Выбор категории теста Phrases
     * @param view Внешнее представление кнопки 3*/
    public void onButtonClickCategory3(View view) {
        HashMap<String, String> phrase  = new HashMap<>();
        phrase.put("i want... [ai wɒnt]", "я хочу...");
        phrase.put("i need... [ai niːd]", "мне нужно... ");
        phrase.put("where is the toilet? [weə iz ðə ˈtɔilit]", "где туалет?");
        phrase.put("excuse me [ikˈskjuːz mi]", "извините меня");
        phrase.put("i'm sorry [aim ˈsɒri]", "мне жаль");
        phrase.put("hello [həˈləʊ]", "здравствуйте");
        phrase.put("good morning [gʊd ˈmɔːniŋ]", "доброе утро");
        phrase.put("good afternoon [gʊd ˈɑːftəˈnuːn]", "добрый день");
        phrase.put("good evening [gʊd ˈiːvniŋ]", "добрый вечер");
        phrase.put("goodbye [ɡʊdˈbʌi]", "досвидания");
        phrase.put("please [pliːz]", "пожалуйста");
        phrase.put("how do you do? [haʊ duː juː duː]", "как дела?");
        phrase.put("how much does it cost? [ˈhaʊ ˈmʌtʃ dʌz it kɒst]", "сколько это стоит");
        phrase.put("thank you [θæŋk juː]", "спасибо");
        phrase.put("here you are [hiə juː ɑː]", "возьмите");
        phrase.put("could i have the bill please? [kʊd ai hæv ði: bil pliːz]", "можно пожалуйста счет?");
        phrase.put("could i have the menu please? [kʊd ai hæv ði: ˈmenjuː pliːz]", "можно пожалуйста меню?");
        phrase.put("help! [help]", "помогите!");
        phrase.put("call the police! [kɔːl ði: pəˈliːs]", "вызовите полицию!");
        phrase.put("call an ambulance! [kɔːl æn ˈæmbjələns]", "вызовите скорую помощ!");
        phrase.put("i don't speak English [ai dəʊnt spiːk ˈiŋɡliʃ]", "я не говорю по-англитйски");
        phrase.put("hi [hai]", "привет");
        phrase.put("it's ok [its ˌəʊˈkei]", "все нормально");
        phrase.put("i don't understand [ai dəʊnt ʌndəˈstand]", "я не понимаю");
        phrase.put("turn left [tɜːn left]", "поверните налево");
        phrase.put("turn right [tɜːn rʌit]", "поверните направо");
        phrase.put("go straight ahead [ɡəʊ streit əˈhɛd]", "идите прямо");
        phrase.put("go back [ɡəʊ ˈbæk]", "идите назад");
        phrase.put("be careful [bi ˈkɛːfʊl]", "будте осторожнее");
        phrase.put("fire! [ˈfaiə]", "пожар!");
        phrase.put("i'm lost [aim lɒst]", "я заблудился");
        phrase.put("Now or never! [naʊ ɔːr ˈnevər]", "Сейчас или никогда!");
        phrase.put("I will pay in cash. [ai wil pei in kæʃ]", "Я заплачу наличными.");
        phrase.put("I will pay by card. [ai wil pei bai kɑːrd]", "Я заплачу картой.");
        phrase.put("What size do you need? [wʌt saiz duː juː niːd]", "Какой размер Вам нужен?");
        phrase.put("Would you like to try it on? [wʊd juː laik tuː trai it ɑːn]", "Вы хотели бы примерить это?");
        phrase.put("How about this one? [haʊ əˈbaʊt ðis wʌn]", "Как насчет этого?");
        phrase.put("Anything else? [ˈeniθiŋ els]", "Что-нибудь еще?");
        phrase.put("Wow, that is cheap! [waʊ ðæt iz tʃiːp]", "Вау! Это дешево!");
        phrase.put("That’s good value. [ðæt iz ɡʊd ˈvæljuː]", "Хорошая цена.");
        phrase.put("Oh, that’s expensive. [əʊ ðæt iz ikˈspensiv]", "Оу, это дороговато.");
        phrase.put("Do you sell ...? [duː juː sel]", "Вы продаете ... ?");
        phrase.put("Are you in the queue? [ɑː juː in ðə kjuː]", "Вы стоите в очереди?");
        phrase.put("Who’s next? [huː iz nekst]", "Кто следующий?");
        phrase.put("Will that be all? [wil ðæt biː ɔːl]", "Это все?");
        phrase.put("Have we met before? [hæv wiː met biˈfɔːr]", "Мы встречались с вами ранее?");
        phrase.put("What should I call you? [wʌt ʃʊd ai kɔːl juː]", "Как мне к вам обращаться?");
        phrase.put("It’s good to have you here! [it iz ɡʊd tuː hæv juː hir]", "Приятно видеть вас здесь!");
        phrase.put("I’d like you to meet someone! [ai wʊd laik tuː miːt ˈsʌmwʌn]", " Я хочу вас кое с кем познакомить!");
        phrase.put("I’ve heard so much about you! [ai hæv səʊ mʌtʃ əˈbaʊt juː]", "Я столько о вас слышал!");
        phrase.put("I haven’t seen you for ages! [ai hæv nɒt siːn juː fɔːr ˈeidʒəz]", "Давно не виделись!");
        phrase.put("Good for you! [ɡʊd fɔːr juː]", "Рад за тебя!");
        phrase.put("Can’t argue with that [kæn nɒt ˈɑːrɡjuː wið ðæt]", "С этим не поспоришь");
        phrase.put("How do you know? [haʊ duː juː nəʊ]", "Откуда ты знаешь?");
        phrase.put("That’s a good question! [ðæt iz ei ɡʊd ˈkwestʃən]", "Хороший вопрос!");
        phrase.put("That would be great! [ðæt wʊd biː ɡreit]", "Было бы здорово!");
        phrase.put("No problem [nəʊ ˈprɑːbləm]", "Без проблем");
        phrase.put("Never mind, it’s fine! [ˈnevər maind it iz fain]", "Не стоит, все в порядке!");
        phrase.put("Anything new going on? [ˈeniθiŋ nuː ˈɡəʊiŋ ɑːn]", "Что новенького?");
        phrase.put("You working the weekend? [juː ˈwɜːrkiŋ ðə ˈwiːkend]", "Работаешь на выходных?");
        phrase.put("It’s so boring! [it iz səʊ ˈbɔːriŋ]", "Скукотища!");
        category = new Category(phrase);
        Intent intent3 =  new  Intent(this, MainActivity3.class);
        intent3.putExtra(Category.class.getSimpleName(),category);
        startActivity(intent3);
    }
    /**Выбор категории теста Food
     * @param view Внешнее представление кнопки 4 */
    public void onButtonClickCategory4(View view) {
        HashMap<String, String> food  = new HashMap<>();
        food.put("apple [ˈæpl]", "яблоко");
        food.put("meat [miːt]", "мясо");
        food.put("milk [milk]", "молоко");
        food.put("water [ˈwɔːtə]", "вода");
        food.put("juice [dʒuːs]", "сок");
        food.put("soda [ˈsəʊdə]", "газировка");
        food.put("beer [biə]", "пиво");
        food.put("tea [tiː]", "чай");
        food.put("coffee [ˈkɒfi]", "кофе");
        food.put("fish [fiʃ]", "рыба");
        food.put("rise [raiz]", "рис");
        food.put("bread [bred]", "хлеб");
        food.put("potato [pəˈteitəʊ]", "картофель");
        food.put("orange [ˈɔːrindʒ]", "апельсин");
        food.put("peach [piːtʃ]", "персик");
        food.put("strawberry [ˈstrɔːberi]", "клубника");
        food.put("wine [wain]", "вино");
        food.put("grape [ɡreip]", "виноград");
        food.put("porridge [ˈpɒridʒ]", "каша");
        food.put("salad [ˈsæləd]", "салат");
        food.put("tomato [təˈmɑːtəʊ]", "помидор");
        food.put("onion [ˈʌnjən]", "лук");
        food.put("sugar [ˈʃʊɡə]", "сахар");
        food.put("carrot [ˈkærət]", "морковь");
        food.put("cucumber [ˈkjuːkʌmbə]", "огурец");
        food.put("cheese [tʃiːz]", "сыр");
        food.put("egg [eɡ]", "яйцо");
        food.put("butter [ˈbʌtə]", "сливочное мало");
        food.put("ice-cream [ais ˈkriːm]", "мороженое");
        food.put("yogurt [ˈjɒɡət]", "йогурт");
        food.put("cake [keik]", "торт");
        food.put("salt [sɔːlt]", "соль");
        food.put("oil [ɔil]", "подсолнечное масло");
        food.put("pepper [ˈpepə]", "перец");
        food.put("bacon [ˈbeikən]","букон");
        food.put("beef [biːf]","говядина");
        food.put("lamb [læm]","ягнятина");
        food.put("chicken [ˈtʃikin]","курица");
        food.put("duck [dʌk]","утка");
        food.put("pork [pɔːk]","свинина");
        food.put("turkey [ˈtɜːki]","индейка");
        food.put("berry [ˈberi]","ягода");
        food.put("caramel [ˈkærəmel]","карамель");
        food.put("honey [ˈhʌni]","мед");
        food.put("jam [dʒæm]","джем");
        food.put("jelly [ˈdʒeli]","желе");
        food.put("lollipop [ˈlɒlipɒp]","леденец");
        food.put("pancake [ˈpænkeik]","блин");
        food.put("pizza [ˈpiːtsə]","пицца");
        food.put("restaurant [ˈrestrɑːnt]","ресторан");
        food.put("ham [hæm]","ветчина");
        food.put("grapefruit [ˈɡreipfruːt]","грейпфрут");
        food.put("cocktail [ˈkɒkteil]","коктейл");
        food.put("burger [ˈbɜːɡə]","бургер");
        food.put("popcorn [ˈpɒpkɔːn]","попкорн");
        food.put("broccoli [ˈbrɒkəli]","броколи");
        food.put("garlic [ˈɡɑːlik]","чеснок");
        food.put("apricot [ˈeiprikɒt]","абрикос");
        food.put("pineapple [ˈpainæpl]","ананас");
        food.put("melon [ˈmelən]","дыня");
        food.put("watermelon [ˈwɔːtəmelən]","арбуз");
        food.put("beans [biːnz]","бобы");
        food.put("avocado [ˌævəˈkɑːdəʊ]","авокадо");
        food.put("sausage [ˈsɒsidʒ]","сосиска");
        category = new Category(food);
        Intent intent3 =  new  Intent(this, MainActivity3.class);
        intent3.putExtra(Category.class.getSimpleName(),category);
        startActivity(intent3);
    }
}