package com.example.enwords;
import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;

import java.util.HashMap;

/** Класс для создания страницы выбора категории */
public class MainActivity2 extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main2);
    }
    Category category;
    /**Выбор категории теста Shopping
     * @param view Внешнее представление кнопки 1*/
    public void onButtonClickCategory1(View view) {
        HashMap<String, String> shopping  = new HashMap<>();
        shopping.put("shop [ʃɒp]", "Магазин");
        shopping.put("clothes [kloʊðz]", "Одежда");
        shopping.put("discount [ˈdiskaʊnt]", "Скидка");
        shopping.put("shop assistant [ʃɒp əˈsistənt]", "Продавец");
        shopping.put("purchase [ˈpəːtʃis]", "Покупка");
        shopping.put("sale [seil]", "Продажа");
        shopping.put("cashier [kæˈʃiə]", "Кассир");
        shopping.put("receipt [riˈsiːt]", "Чек");
        shopping.put("cash [kæʃ]", "Наличные");
        shopping.put("credit card [ˈkrɛdit kɑːd]", "Кредитная карта");
        shopping.put("delivery [diˈlivəri]", "Доставка");
        shopping.put("T-shirt [ˈtiːʃəːt]", "Футболка");
        shopping.put("shirt [ʃəːt]", "Рубашка");
        shopping.put("trousers [ˈtraʊzəz]", "Брюки");
        shopping.put("bag [bæɡ]", "Сумка");
        shopping.put("wool [wʊl]", "Шерсть");
        shopping.put("cotton [ˈkɑːtn]", "Хлопок");
        shopping.put("leather [ˈlɛðə]", "Кожа");
        shopping.put("jacket [ˈdʒakit]", "Куртка");
        shopping.put("shoes [ʃuːz]", "Туфли");
        shopping.put("jeans [dʒiːnz]", "Джинсы");
        shopping.put("shorts [ʃɔːts]", "Шорты");
        shopping.put("socks [ˈsɒks]", "Носки");
        shopping.put("underwear [ˈʌndəwɛː]", "Нижнее белье");
        shopping.put("money [ˈmʌni]", "Деньги");
        shopping.put("trolley [ˈtrɒli]", "Тележка");
        shopping.put("basket [ˈbɑːskit]", "Корзина");
        shopping.put("fitting room [ˈfitiŋ ruːm]", "Примерочная");
        shopping.put("chip [tʃip]", "Дешевый");
        shopping.put("expensive [ikˈspɛnsiv]", "Дорогой");
        shopping.put("coins [kɔinz]", "Монеты");
        shopping.put("price [prʌis]", "Цена");
        shopping.put("wallet [ˈwɑːlit]", "Мужской кошелек");
        shopping.put("escalator [ˈeskəleitər]", "Эскалатор");
        shopping.put("lift [lift]", "Лифт");
        shopping.put("products [ˈprɑːdəkts]", "Продукты");
        shopping.put("bookshop [ˈbʊkʃɑːp]", "Книжный магазин");
        shopping.put("supermarket [ˈsuːpərmɑːrkət]", "Супермаркет");
        shopping.put("pet shop [pet ʃɑːp]", "Зоомагазин");
        shopping.put("tea-house [ˈtiːhaʊs]", "Чайный магазин");
        shopping.put("post office [pəʊst ˈɔːfis]", "Почтовое отделение");
        shopping.put("market [ˈmɑːrkit]", "Рынок");
        shopping.put("record shop [ˈrekərd ʃɑːp]", "Музыкальный магазин");
        shopping.put("scarf [skɑːrf]", "Шарф");
        shopping.put("toy store [tɔi stɔːr]", "Магазин игрушек");
        shopping.put("hat [hæt]", "Шапка");
        shopping.put("chemist [ˈkemist]", "Аптека");
        shopping.put("online store [ɒnˈlain stɔːr]", "Онлайн-магазин");
        shopping.put("hoody [ˈhʊdi]", "Толстовка");
        shopping.put("manager [ˈmænidʒər]", "Менеджер");
        shopping.put("blouse [blaʊs]", "Кофта");
        shopping.put("rip-off [ˈrip ɒf]", "Грабеж");
        shopping.put("bargain [ˈbɑːrɡən]", "Выгодная покупка");
        shopping.put("price tag [prais tæɡ]", "Ценник");
        shopping.put("department store [diˈpɑːrtmənt stɔːr]", "Универмаг");
        shopping.put("bakery [ˈbeikəri]", "Булочная");
        shopping.put("stationary shop [ˈsteiʃənerɪ ʃɑːp]", "Магазин с канцелярией");
        shopping.put("florist shop [ˈflɔːrist ʃɑːp]", "Цветочный магазин");
        shopping.put("clearance sale [ˈklirəns seil]", "Полная распродажа");
        shopping.put("label [ˈleibl]", "Ярлык");
        shopping.put("stall [stɔːl]", "Киоск");
        shopping.put("booth [buːθ]", "Ларек");
        shopping.put("gloves [ɡlʌvz]", "Перчатки");
        category = new Category(shopping);
        Intent intent3 =  new  Intent(this, MainActivity3.class);
        intent3.putExtra(Category.class.getSimpleName(),category);
        startActivity(intent3);
    }
    /**Выбор категории теста Verbs
     *@param view  Внешнее представление кнопки 2*/
    public void onButtonClickCategory2(View view) {
        HashMap<String, String> verb  = new HashMap<>();
        verb.put("do [duː]", "Делать");
        verb.put("go [ɡəʊ]", "Идти");
        verb.put("work [wɜːk]", "Работать");
        verb.put("eat [iːt]", "Кушать");
        verb.put("see [siː]", "Видеть");
        verb.put("watch [wɒtʃ]", "Смотреть");
        verb.put("think [θiŋk]", "Думать");
        verb.put("buy [bai]", "Покупать");
        verb.put("choose [tʃuːz]", "Выбирать");
        verb.put("say [sei]", "Сказать");
        verb.put("speak [spiːk]", "Разговаривать");
        verb.put("feel [fiːl]", "Чувствовать");
        verb.put("play [plei]", "Играть");
        verb.put("teach [tiːtʃ]", "Учить кого-то");
        verb.put("sleep [sliːp]", "Спать");
        verb.put("give [ɡiv]", "Давать");
        verb.put("take [teik]", "Брать");
        verb.put("have [hæv]", "Иметь");
        verb.put("hear [hiə]", "Слышать");
        verb.put("love [lʌv]", "Любить");
        verb.put("live [liv]", "Жить");
        verb.put("listen [ˈlisn]", "Слушать");
        verb.put("want [wɒnt]", "Хотеть");
        verb.put("use [juːz]", "Использовать");
        verb.put("ask [ɑːsk]", "Спрашивать");
        verb.put("get [ɡet]", "Получать");
        verb.put("run [rʌn]", "Бежать");
        verb.put("pay [pei]", "Платить");
        verb.put("help [help]", "Помогать");
        verb.put("win [win]", "Побеждать");
        verb.put("lose [luːz]", "Терять");
        verb.put("sell [sel]", "Продавать");
        verb.put("kill [kil]", "Убивать");
        verb.put("cut [kʌt]", "Резать");
        verb.put("stop [stɒp]", "Остановить");
        verb.put("travel [ˈtrævl]", "Путешествовать");
        verb.put("drive [draiv]", "Ехать");
        verb.put("accept [əkˈsept]","Принимать");
        verb.put("add [æd]","Добавлять");
        verb.put("agree [əˈɡriː]","Соглашаться");
        verb.put("answer [ˈɑːnsə]","Отвечать");
        verb.put("become [biˈkʌm]","Становиться");
        verb.put("begin [biˈɡin]","Начинать");
        verb.put("believe [biˈliːv]","Верить");
        verb.put("borrow [ˈbɒrəʊ]","Занимать");
        verb.put("break [breik]","Ломать");
        verb.put("cancel [ˈkænsl]","Отменять");
        verb.put("change [tʃeindʒ]","Менять");
        verb.put("clean [kliːn]","Чистить");
        verb.put("close [kləʊz]","Закрывать");
        verb.put("come [kʌm]","Приходить");
        verb.put("count [kaʊnt]","Считать");
        verb.put("dance [dɑːns]","Танцевать");
        verb.put("decide [diˈsaid]","Решать");
        verb.put("drink [driŋk]","Пить");
        verb.put("fly [flai]","Летать");
        verb.put("learn [lɜːn]","Учить");
        verb.put("lie [lai]","Лгать");
        verb.put("own [əʊn]","Иметь");
        verb.put("open [ˈəʊpən]","Открывать");
        verb.put("read [riːd]","Читать");
        verb.put("remember [riˈmembə]","Помнить");
        verb.put("swim [swim]","Плыть");
        verb.put("write [rait]","Писать");
        verb.put("wear [weə]","Носить");
        verb.put("try [trai]","Пробовать");
        verb.put("translate [trænsˈleit]","Переводить");
        category = new Category(verb);
        Intent intent3 =  new  Intent(this, MainActivity3.class);
        intent3.putExtra(Category.class.getSimpleName(),category);
        startActivity(intent3);
    }
    /**Выбор категории теста Phrases
     * @param view Внешнее представление кнопки 3*/
    public void onButtonClickCategory3(View view) {
        HashMap<String, String> phrase  = new HashMap<>();
        phrase.put("i want... [ai wɒnt]", "Я хочу...");
        phrase.put("i need... [ai niːd]", "Мне нужно... ");
        phrase.put("where is the toilet? [weə iz ðə ˈtɔilit]", "Где туалет?");
        phrase.put("excuse me [ikˈskjuːz mi]", "Извините меня");
        phrase.put("i'm sorry [aim ˈsɒri]", "Мне жаль");
        phrase.put("hello [həˈləʊ]", "Здравствуйте");
        phrase.put("good morning [gʊd ˈmɔːniŋ]", "Доброе утро");
        phrase.put("good afternoon [gʊd ˈɑːftəˈnuːn]", "Добрый день");
        phrase.put("good evening [gʊd ˈiːvniŋ]", "Добрый вечер");
        phrase.put("goodbye [ɡʊdˈbʌi]", "До свидания");
        phrase.put("please [pliːz]", "Пожалуйста");
        phrase.put("how do you do? [haʊ duː juː duː]", "Как дела?");
        phrase.put("how much does it cost? [ˈhaʊ ˈmʌtʃ dʌz it kɒst]", "Сколько это стоит");
        phrase.put("thank you [θæŋk juː]", "Спасибо");
        phrase.put("here you are [hiə juː ɑː]", "Возьмите");
        phrase.put("could i have the bill please? [kʊd ai hæv ði: bil pliːz]", "Можно пожалуйста счет?");
        phrase.put("could i have the menu please? [kʊd ai hæv ði: ˈmenjuː pliːz]", "Можно пожалуйста меню?");
        phrase.put("help! [help]", "Помогите!");
        phrase.put("call the police! [kɔːl ði: pəˈliːs]", "Вызовите полицию!");
        phrase.put("call an ambulance! [kɔːl æn ˈæmbjələns]", "Вызовите скорую помощ!");
        phrase.put("i don't speak English [ai dəʊnt spiːk ˈiŋɡliʃ]", "Я не говорю по-англитйски");
        phrase.put("hi [hai]", "Привет");
        phrase.put("it's ok [its ˌəʊˈkei]", "Все нормально");
        phrase.put("i don't understand [ai dəʊnt ʌndəˈstand]", "Я не понимаю");
        phrase.put("turn left [tɜːn left]", "Поверните налево");
        phrase.put("turn right [tɜːn rʌit]", "Поверните направо");
        phrase.put("go straight ahead [ɡəʊ streit əˈhɛd]", "Идите прямо");
        phrase.put("go back [ɡəʊ ˈbæk]", "Идите назад");
        phrase.put("be careful [bi ˈkɛːfʊl]", "Будте осторожнее");
        phrase.put("fire! [ˈfaiə]", "Пожар!");
        phrase.put("i'm lost [aim lɒst]", "Я заблудился");
        phrase.put("Now or never! [naʊ ɔːr ˈnevər]", "Сейчас или никогда!");
        phrase.put("I will pay in cash. [ai wil pei in kæʃ]", "Я заплачу наличными.");
        phrase.put("I will pay by card. [ai wil pei bai kɑːrd]", "Я заплачу картой.");
        phrase.put("What size do you need? [wʌt saiz duː juː niːd]", "Какой размер Вам нужен?");
        phrase.put("Would you like to try it on? [wʊd juː laik tuː trai it ɑːn]", "Вы хотели бы примерить это?");
        phrase.put("How about this one? [haʊ əˈbaʊt ðis wʌn]", "Как насчет этого?");
        phrase.put("Anything else? [ˈeniθiŋ els]", "Что-нибудь еще?");
        phrase.put("Wow, that is cheap! [waʊ ðæt iz tʃiːp]", "Вау! Это дешево!");
        phrase.put("That’s good value. [ðæt iz ɡʊd ˈvæljuː]", "Хорошая цена.");
        phrase.put("Oh, that’s expensive. [əʊ ðæt iz ikˈspensiv]", "Оу, это дороговато.");
        phrase.put("Do you sell ...? [duː juː sel]", "Вы продаете ... ?");
        phrase.put("Are you in the queue? [ɑː juː in ðə kjuː]", "Вы стоите в очереди?");
        phrase.put("Who’s next? [huː iz nekst]", "Кто следующий?");
        phrase.put("Will that be all? [wil ðæt biː ɔːl]", "Это все?");
        phrase.put("Have we met before? [hæv wiː met biˈfɔːr]", "Мы встречались с вами ранее?");
        phrase.put("What should I call you? [wʌt ʃʊd ai kɔːl juː]", "Как мне к вам обращаться?");
        phrase.put("It’s good to have you here! [it iz ɡʊd tuː hæv juː hir]", "Приятно видеть вас здесь!");
        phrase.put("I’d like you to meet someone! [ai wʊd laik tuː miːt ˈsʌmwʌn]", " Я хочу вас кое с кем познакомить!");
        phrase.put("I’ve heard so much about you! [ai hæv səʊ mʌtʃ əˈbaʊt juː]", "Я столько о вас слышал!");
        phrase.put("I haven’t seen you for ages! [ai hæv nɒt siːn juː fɔːr ˈeidʒəz]", "Давно не виделись!");
        phrase.put("Good for you! [ɡʊd fɔːr juː]", "Рад за тебя!");
        phrase.put("Can’t argue with that [kæn nɒt ˈɑːrɡjuː wið ðæt]", "С этим не поспоришь");
        phrase.put("How do you know? [haʊ duː juː nəʊ]", "Откуда ты знаешь?");
        phrase.put("That’s a good question! [ðæt iz ei ɡʊd ˈkwestʃən]", "Хороший вопрос!");
        phrase.put("That would be great! [ðæt wʊd biː ɡreit]", "Было бы здорово!");
        phrase.put("No problem [nəʊ ˈprɑːbləm]", "Без проблем");
        phrase.put("Never mind, it’s fine! [ˈnevər maind it iz fain]", "Не стоит, все в порядке!");
        phrase.put("Anything new going on? [ˈeniθiŋ nuː ˈɡəʊiŋ ɑːn]", "Что новенького?");
        phrase.put("You working the weekend? [juː ˈwɜːrkiŋ ðə ˈwiːkend]", "Работаешь на выходных?");
        phrase.put("It’s so boring! [it iz səʊ ˈbɔːriŋ]", "Скукотища!");
        category = new Category(phrase);
        Intent intent3 =  new  Intent(this, MainActivity3.class);
        intent3.putExtra(Category.class.getSimpleName(),category);
        startActivity(intent3);
    }
    /**Выбор категории теста Food
     * @param view Внешнее представление кнопки 4 */
    public void onButtonClickCategory4(View view) {
        HashMap<String, String> food  = new HashMap<>();
        food.put("apple [ˈæpl]", "Яблоко");
        food.put("meat [miːt]", "Мясо");
        food.put("milk [milk]", "Молоко");
        food.put("water [ˈwɔːtə]", "Вода");
        food.put("juice [dʒuːs]", "Сок");
        food.put("soda [ˈsəʊdə]", "Газировка");
        food.put("beer [biə]", "Пиво");
        food.put("tea [tiː]", "Чай");
        food.put("coffee [ˈkɒfi]", "Кофе");
        food.put("fish [fiʃ]", "Рыба");
        food.put("rise [raiz]", "Рис");
        food.put("bread [bred]", "Хлеб");
        food.put("potato [pəˈteitəʊ]", "Картофель");
        food.put("orange [ˈɔːrindʒ]", "Апельсин");
        food.put("peach [piːtʃ]", "Персик");
        food.put("strawberry [ˈstrɔːberi]", "Клубника");
        food.put("wine [wain]", "Вино");
        food.put("grape [ɡreip]", "Виноград");
        food.put("porridge [ˈpɒridʒ]", "Каша");
        food.put("salad [ˈsæləd]", "Салат");
        food.put("tomato [təˈmɑːtəʊ]", "Помидор");
        food.put("onion [ˈʌnjən]", "Лук");
        food.put("sugar [ˈʃʊɡə]", "Сахар");
        food.put("carrot [ˈkærət]", "Морковь");
        food.put("cucumber [ˈkjuːkʌmbə]", "Огурец");
        food.put("cheese [tʃiːz]", "Сыр");
        food.put("egg [eɡ]", "Яйцо");
        food.put("butter [ˈbʌtə]", "Сливочное мало");
        food.put("ice-cream [ais ˈkriːm]", "Мороженое");
        food.put("yogurt [ˈjɒɡət]", "Йогурт");
        food.put("cake [keik]", "Торт");
        food.put("salt [sɔːlt]", "Соль");
        food.put("oil [ɔil]", "Подсолнечное масло");
        food.put("pepper [ˈpepə]", "Перец");
        food.put("bacon [ˈbeikən]","Бекон");
        food.put("beef [biːf]","Говядина");
        food.put("lamb [læm]","Ягнятина");
        food.put("chicken [ˈtʃikin]","Курица");
        food.put("duck [dʌk]","Утка");
        food.put("pork [pɔːk]","Свинина");
        food.put("turkey [ˈtɜːki]","Индейка");
        food.put("berry [ˈberi]","Ягода");
        food.put("caramel [ˈkærəmel]","Карамель");
        food.put("honey [ˈhʌni]","Мед");
        food.put("jam [dʒæm]","Джем");
        food.put("jelly [ˈdʒeli]","Желе");
        food.put("lollipop [ˈlɒlipɒp]","Леденец");
        food.put("pancake [ˈpænkeik]","Блин");
        food.put("pizza [ˈpiːtsə]","Пицца");
        food.put("restaurant [ˈrestrɑːnt]","Ресторан");
        food.put("ham [hæm]","Ветчина");
        food.put("grapefruit [ˈɡreipfruːt]","Грейпфрут");
        food.put("cocktail [ˈkɒkteil]","Коктейл");
        food.put("burger [ˈbɜːɡə]","Бургер");
        food.put("popcorn [ˈpɒpkɔːn]","Попкорн");
        food.put("broccoli [ˈbrɒkəli]","Броколи");
        food.put("garlic [ˈɡɑːlik]","Чеснок");
        food.put("apricot [ˈeiprikɒt]","Абрикос");
        food.put("pineapple [ˈpainæpl]","Ананас");
        food.put("melon [ˈmelən]","Дыня");
        food.put("watermelon [ˈwɔːtəmelən]","Арбуз");
        food.put("beans [biːnz]","Бобы");
        food.put("avocado [ˌævəˈkɑːdəʊ]","Авокадо");
        food.put("sausage [ˈsɒsidʒ]","Сосиска");
        category = new Category(food);
        Intent intent3 =  new  Intent(this, MainActivity3.class);
        intent3.putExtra(Category.class.getSimpleName(),category);
        startActivity(intent3);
    }
}